
<h3>Adicionar dados de Portfólio Dev</h3>

<form method="POST" action="adicionar_action.php">
    <label>
        Título Do Projeto:<br/>
        <input type="text" name="name" />        
    </label><br/><br/>
    <label>
        Linguagem Desenvolvida:<br/>
        <input type="text" name="secname" />        
    </label><br/><br/>
    <label>
        Descrição:<br/>
        <input type="text" name="tername"/>        
    </label><br/><br/>

    <input type="submit" value="Adicionar" />
</form>

